openapi: 3.0.0
paths:
  /:
    get:
      description: Returns a simple API welcome message.
      operationId: AppController_getHello
      parameters: []
      responses:
        '200':
          description: ''
      summary: Welcome endpoint
      tags:
        - App
  /health:
    get:
      description: Checks if the Backend is running.
      operationId: AppController_health
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
      summary: Health check
      tags:
        - App
info:
  title: '@Gyp6.sale - Furniture.Wholesale API'
  description: API Backend for Furniture.Wholesale
  version: 1.0.0
  contact: {}
tags: []
servers: []
components:
  securitySchemes:
    bearer:
      scheme: bearer
      bearerFormat: JWT
      type: http
  schemas:
    HealthResponse:
      type: object
      properties:
        status:
          type: string
          example: ok
        timestamp:
          type: string
          example: '2026-03-21T21:30:00.000Z'
      required:
        - status
        - timestamp
