FROM oven/bun:1.2-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production

# 1. Створюємо безпечного користувача
RUN addgroup --system --gid 1001 nodejs \
    && adduser --system --uid 1001 nestjs

# 2. Передаємо права на саму папку /app користувачу nestjs (робимо це як root!)
RUN chown nestjs:nodejs /app

# 3. Копіюємо код (код важить мало, копіювання з chown пролетить миттєво)
COPY --chown=nestjs:nodejs . .

# 4. Ось тепер безпечно перемикаємось
USER nestjs

# 5. Ставимо прод-залежності (тепер папка доступна на запис, mkdir спрацює)
RUN bun install --production --frozen-lockfile

# 6. Офіційний запуск генератора Prisma
RUN bunx prisma generate --schema=./src/infrastructure/prisma/schema.prisma

EXPOSE 4200

CMD ["bun", "dist/src/main.js"]
